import { useMemo, useState } from 'react';
import { useTheme } from '../../theme/ThemeContext.jsx';
import { ui } from '../../theme/ui.js';
import { useFleetManager } from '../../hooks/useFleetManager.js';
import Drawer from './Drawer.jsx';

const STATE_COLOR = (P) => ({
    RUNNING: P.success,
    ONLINE: P.success,
    STARTING: P.warning,
    STOPPING: P.warning,
    STOPPED: P.textDim,
    CRASHED: P.danger,
});

export default function AmrDrawer({ status, onClose }) {
    const { palette: P } = useTheme();
    const S = ui(P);
    const stateColor = STATE_COLOR(P);
    const { command, busy, managerAvailable } = useFleetManager();
    const amrs = useMemo(() => (status ? status.amrs : []), [status]);
    const [form, setForm] = useState({ id: '', x: '', y: '' });

    const nextDefaultId = useMemo(() => {
        const used = new Set(amrs.map((a) => a.id));
        let n = 1;
        while (used.has(`AMR${n}`)) n += 1;
        return `AMR${n}`;
    }, [amrs]);

    const isBusy = (path) => busy[`POST:${path}`] || busy[`DELETE:${path}`];

    const create = async (e) => {
        e.preventDefault();
        const id = (form.id || '').trim();
        if (!id) return;
        await command('/api/amrs', {
            method: 'POST',
            body: { id, x: Number.parseFloat(form.x) || 0, y: Number.parseFloat(form.y) || 0 },
        });
        setForm({ id: '', x: '', y: '' });
    };

    const remove = async (id) => {
        if (!window.confirm(`Remove ${id}? The AMR will be deleted from the configured fleet.`)) return;
        await command(`/api/amrs/${encodeURIComponent(id)}`, { method: 'DELETE' });
    };

    return (
        <Drawer title="AMR MANAGEMENT" subtitle={`${amrs.length} configured AMR processes`} onClose={onClose} width={520}>
            <div style={{ padding: 12 }}>
                {!managerAvailable && (
                    <div style={{ fontSize: 11, color: P.danger, marginBottom: 10 }}>
                        Fleet Manager unavailable — AMR process lifecycle controls disabled.
                    </div>
                )}

                <div style={S.sectionTitle}>ROSTER</div>
                <div style={{ fontSize: 10, color: P.textDim, marginBottom: 8 }}>
                    The warehouse roster (positions, ids) is generated by the coordinator from preset +
                    demo formula. Adding an AMR registers a process; start it and it will join the roster
                    after the coordinator restarts.
                </div>

                {amrs.length === 0 && <div style={{ fontSize: 11, color: P.textMuted, marginBottom: 8 }}>No AMRs configured.</div>}

                {amrs.map((a) => {
                    const rowBusy = isBusy(`/api/amrs/${a.id}/start`) || isBusy(`/api/amrs/${a.id}/stop`) ||
                        isBusy(`/api/amrs/${a.id}/restart`) || isBusy(`/api/amrs/${a.id}`);
                    const color = stateColor[a.state] || P.textDim;
                    return (
                        <div key={a.id} style={{ ...S.card, marginBottom: 6 }}>
                            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                                <span style={S.dot(color)} />
                                <span style={{ fontSize: 13, fontWeight: 'bold' }}>{a.id}</span>
                                <span style={{ fontSize: 10, color }}>
                                    {a.state === 'RUNNING' ? 'ONLINE' : (a.state || 'STOPPED')}
                                </span>
                                {a.pid && <span style={{ fontSize: 10, color: P.textDim }}>pid {a.pid}</span>}
                                <span style={{ flex: 1 }} />
                                {(a.state === 'RUNNING' || a.state === 'STARTING' || a.state === 'STOPPING') ? (
                                    <button style={S.button('danger')} disabled={rowBusy} onClick={() => command(`/api/amrs/${encodeURIComponent(a.id)}/stop`)}>
                                        STOP
                                    </button>
                                ) : (
                                    <button style={S.button('primary')} disabled={rowBusy} onClick={() => command(`/api/amrs/${encodeURIComponent(a.id)}/start`)}>
                                        START
                                    </button>
                                )}
                                <button style={S.button()} disabled={rowBusy} onClick={() => command(`/api/amrs/${encodeURIComponent(a.id)}/restart`)}>
                                    RESTART
                                </button>
                                <button style={S.button('danger')} disabled={rowBusy} onClick={() => remove(a.id)}>
                                    REMOVE
                                </button>
                            </div>
                            {a.lastError && (
                                <div style={{ fontSize: 10, color: P.logErr, marginTop: 2, wordBreak: 'break-all' }}>⚠ {a.lastError}</div>
                            )}
                        </div>
                    );
                })}

                <form onSubmit={create} style={{ marginTop: 12 }}>
                    <div style={S.sectionTitle}>+ CREATE AMR</div>
                    <div style={{ display: 'flex', gap: 6, alignItems: 'center', marginTop: 6 }}>
                        <input
                            style={S.input}
                            value={form.id}
                            onChange={(e) => setForm({ ...form, id: e.target.value })}
                            placeholder={nextDefaultId}
                        />
                        <input
                            style={{ ...S.input, width: 70 }}
                            value={form.x}
                            onChange={(e) => setForm({ ...form, x: e.target.value })}
                            placeholder="x"
                            type="number"
                            step="0.5"
                        />
                        <input
                            style={{ ...S.input, width: 70 }}
                            value={form.y}
                            onChange={(e) => setForm({ ...form, y: e.target.value })}
                            placeholder="y"
                            type="number"
                            step="0.5"
                        />
                        <button style={S.button('primary')} type="submit" disabled={!managerAvailable}>Create</button>
                    </div>
                    <div style={{ fontSize: 10, color: P.textDim, marginTop: 6 }}>
                        x/y are the initial spawn position used by the coordinator on restart; warehouse layout
                        itself is backend-authoritative.
                    </div>
                </form>
            </div>
        </Drawer>
    );
}